### ISSUE TITLE
A little typo

### ISSUE THREAD

**Issue by Dementiy** [testdrivenio/simple-task-queue#1]
Typo:
https://github.com/testdrivenio/simple-task-queue/blob/d3b173239c501f32548010987254c64d3cae4963/tasks.py#L41

I think that `sys.argv` will be enough for this example:

```python
import sys
# ...
if __name__ == '__main__':
    get_word_counts(sys.argv[1])
```

**Comment by mjhea0** [comment]
Good catch. Want to open a PR?
